# Generated by Django 3.0.4 on 2020-04-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='players',
            field=models.ManyToManyField(to='main_app.Player'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='sponsors',
            field=models.ManyToManyField(to='main_app.Sponsor'),
        ),
    ]
