# Generated by Django 3.0.4 on 2020-04-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200409_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='sponsor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Sponsor'),
            preserve_default=False,
        ),
    ]
