# Generated by Django 3.0.4 on 2020-04-11 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200410_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='player',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='sponsor',
        ),
        migrations.CreateModel(
            name='Photo_sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Player')),
            ],
        ),
    ]
