# Generated by Django 3.0.4 on 2020-04-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200410_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'ordering': ['date']},
        ),
    ]
